### ISSUE TITLE
Could not detect start of redis-server with Redis >= 4.0

### ISSUE THREAD

**Issue by astj** [soh335/go-test-redisserver#7]
Report from Travis-ci failure log of our project: https://travis-ci.org/mackerelio/mackerel-agent-plugins/builds/273824826#L1605

Currently go-test-redisserver detects redis-server's start by detecting "The server is now ready to accept connections" text:
https://github.com/soh335/go-test-redisserver/blob/master/redistest.go#L216

This works fine with Redis 3.2:
https://github.com/antirez/redis/blob/3.2/src/server.c#L4116
But Redis 4.0 may return different text:
https://github.com/antirez/redis/blob/4.0/src/server.c#L3837

Maybe case-insensitive match (like [test helper for Redis](https://github.com/antirez/redis/blob/4.0/tests/support/server.tcl#L281) does) or check both "Ready ~" and "The server is ~" will solve this issue.

**Comment by soh335** [comment]
@astj Thanks for reporting. Cloud you create case-instentive match patch ?

**Comment by astj** [comment]
@soh335 Okay. I opened #8.

**Comment by soh335** [comment]
@astj merged

**Comment by astj** [comment]
Thank you! I confirmed it worked well: https://travis-ci.org/mackerelio/mackerel-agent-plugins/builds/274138275
